version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts-centos7
    restart: always
    ports:
      - 9090:8080
    environment:
      DOCKER_HOST: 172.17.0.1
    volumes:
      - ./jenkins-data:/var/jenkins_home

  sonarqube:
    image: sonarqube:7.9-community
    restart: always
    ports:
      - 9000:9000
    environment:
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
      - sonar.jdbc.url=jdbc:postgresql://postgres/sonarqube
    volumes:
      - ./sonar-data:/opt/sonarqube/data
      - ./sonar-extensions:/opt/sonarqube/extensions

  postgres:
    image: postgres:12.3
    restart: always
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
